# Generated by Django 4.2.13 on 2024-07-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comment_post_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comment_images/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='images',
            field=models.ManyToManyField(to='core.commentimage'),
        ),
    ]
