# Generated by Django 4.2.13 on 2024-07-28 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_commentimage_comment_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='images',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='core.commentimage'),
        ),
    ]
